FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# АПИ для мобильного приложения

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Кто на свете всех взрывнее?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "answer":"Ясина"
            }
        ]

## Questions Collection [/bla]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]